name: flutter_transmission
description: Flutter package to talk to a Transmission torrent instance, for a pure dart package please check [transmission](https://github.com/mylisabox/transmission)
version: 0.1.0
homepage: https://github.com/mylisabox/flutter_transmission

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  transmission: ">=0.1.0 <1.0.0"
   # path: '../transmission'
  provider: ">=5.0.0 <6.0.0"
  mobx: ">=2.0.1 <3.0.0"
  dio: ">=4.0.0 <5.0.0"
  flutter_mobx: ">=2.0.0 <3.0.0"
  flutter_hooks: ">=0.16.0 <1.0.0"
  flutter_svg: ">=0.21.0 <1.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  mobx_codegen: ">=2.0.1 <3.0.0"
  build_runner: ">=1.10.1 <2.0.0"
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
     - assets/images/
